### ISSUE TITLE
Broken localization / UI.

### ISSUE THREAD

**Issue by Zazou89** [sct/overseerr#1085]
#### Description
Can't access to UI : _Internal server error._
#### Version

Commit Tag: 6072e8aa9a0f84e50c44a92af303aad15b5f3021

#### Device

What device were you using when you encountered this issue? Please provide this information to help us reproduce and investigate the bug.

- **Platform:** docker

#### Additional Context
`RangeError: 'fr_FR' is not a structurally valid language tag
at CanonicalizeLocaleList (/app/node_modules/intl/lib/core.js:1270:61)
at Object.<anonymous> (/app/node_modules/intl/lib/core.js:2129:28)
at Object.createIntl (/app/node_modules/@formatjs/intl/src/create-intl.js:46:33)
at Object.createIntl (/app/node_modules/react-intl/src/components/provider.js:63:27)
at new IntlProvider (/app/node_modules/react-intl/src/components/provider.js:83:27)
at d (/app/node_modules/react-dom/cjs/react-dom-server.node.production.min.js:33:320)
at bb (/app/node_modules/react-dom/cjs/react-dom-server.node.production.min.js:36:16)
at a.b.render (/app/node_modules/react-dom/cjs/react-dom-server.node.production.min.js:42:43)
at a.b.read (/app/node_modules/react-dom/cjs/react-dom-server.node.production.min.js:41:83)
at exports.renderToString (/app/node_modules/react-dom/cjs/react-dom-server.node.production.min.js:52:138)
at Object.renderPage (/app/node_modules/next/dist/next-server/server/render.js:53:851)
at Function.getInitialProps (/app/.next/server/pages/_document.js:282:19)
at Function.getInitialProps (/app/.next/server/pages/_document.js:789:85)
at loadGetInitialProps (/app/node_modules/next/dist/next-server/lib/utils.js:5:101)
at renderToHTML (/app/node_modules/next/dist/next-server/server/render.js:53:1142)
at processTicksAndRejections (internal/process/task_queues.js:93:5)
RangeError: 'fr_FR' is not a structurally valid language tag
at CanonicalizeLocaleList (/app/node_modules/intl/lib/core.js:1270:61)
at Object.<anonymous> (/app/node_modules/intl/lib/core.js:2129:28)
at Object.createIntl (/app/node_modules/@formatjs/intl/src/create-intl.js:46:33)
at Object.createIntl (/app/node_modules/react-intl/src/components/provider.js:63:27)
at new IntlProvider (/app/node_modules/react-intl/src/components/provider.js:83:27)
at d (/app/node_modules/react-dom/cjs/react-dom-server.node.production.min.js:33:320)
at bb (/app/node_modules/react-dom/cjs/react-dom-server.node.production.min.js:36:16)
at a.b.render (/app/node_modules/react-dom/cjs/react-dom-server.node.production.min.js:42:43)
at a.b.read (/app/node_modules/react-dom/cjs/react-dom-server.node.production.min.js:41:83)
at exports.renderToString (/app/node_modules/react-dom/cjs/react-dom-server.node.production.min.js:52:138)
at Object.renderPage (/app/node_modules/next/dist/next-server/server/render.js:53:851)
at Function.getInitialProps (/app/.next/server/pages/_document.js:282:19)
at Function.getInitialProps (/app/.next/server/pages/_document.js:789:85)
at loadGetInitialProps (/app/node_modules/next/dist/next-server/lib/utils.js:5:101)
at renderToHTML (/app/node_modules/next/dist/next-server/server/render.js:53:1142)
at processTicksAndRejections (internal/process/task_queues.js:93:5)
2021-03-04T19:55:27.122Z [[32minfo[39m][Plex Sync]: Recently Added Scan Complete
2021-03-04T19:55:27.122Z [[32minfo[39m][Plex Sync]: Recently Added Scan Complete
RangeError: 'fr_FR' is not a structurally valid language tag
at CanonicalizeLocaleList (/app/node_modules/intl/lib/core.js:1270:61)
at Object.<anonymous> (/app/node_modules/intl/lib/core.js:2129:28)
at Object.createIntl (/app/node_modules/@formatjs/intl/src/create-intl.js:46:33)
at Object.createIntl (/app/node_modules/react-intl/src/components/provider.js:63:27)
at new IntlProvider (/app/node_modules/react-intl/src/components/provider.js:83:27)
at d (/app/node_modules/react-dom/cjs/react-dom-server.node.production.min.js:33:320)
at bb (/app/node_modules/react-dom/cjs/react-dom-server.node.production.min.js:36:16)
at a.b.render (/app/node_modules/react-dom/cjs/react-dom-server.node.production.min.js:42:43)
at a.b.read (/app/node_modules/react-dom/cjs/react-dom-server.node.production.min.js:41:83)
at exports.renderToString (/app/node_modules/react-dom/cjs/react-dom-server.node.production.min.js:52:138)
at Object.renderPage (/app/node_modules/next/dist/next-server/server/render.js:53:851)
at Function.getInitialProps (/app/.next/server/pages/_document.js:282:19)
at Function.getInitialProps (/app/.next/server/pages/_document.js:789:85)
at loadGetInitialProps (/app/node_modules/next/dist/next-server/lib/utils.js:5:101)
at renderToHTML (/app/node_modules/next/dist/next-server/server/render.js:53:1142)
at processTicksAndRejections (internal/process/task_queues.js:93:5)
RangeError: 'fr_FR' is not a structurally valid language tag
at CanonicalizeLocaleList (/app/node_modules/intl/lib/core.js:1270:61)
at Object.<anonymous> (/app/node_modules/intl/lib/core.js:2129:28)
at Object.createIntl (/app/node_modules/@formatjs/intl/src/create-intl.js:46:33)
at Object.createIntl (/app/node_modules/react-intl/src/components/provider.js:63:27)
at new IntlProvider (/app/node_modules/react-intl/src/components/provider.js:83:27)
at d (/app/node_modules/react-dom/cjs/react-dom-server.node.production.min.js:33:320)
at bb (/app/node_modules/react-dom/cjs/react-dom-server.node.production.min.js:36:16)
at a.b.render (/app/node_modules/react-dom/cjs/react-dom-server.node.production.min.js:42:43)
at a.b.read (/app/node_modules/react-dom/cjs/react-dom-server.node.production.min.js:41:83)
at exports.renderToString (/app/node_modules/react-dom/cjs/react-dom-server.node.production.min.js:52:138)
at Object.renderPage (/app/node_modules/next/dist/next-server/server/render.js:53:851)
at Function.getInitialProps (/app/.next/server/pages/_document.js:282:19)
at Function.getInitialProps (/app/.next/server/pages/_document.js:789:85)
at loadGetInitialProps (/app/node_modules/next/dist/next-server/lib/utils.js:5:101)
at renderToHTML (/app/node_modules/next/dist/next-server/server/rende`

**Comment by samwiseg0** [comment]
Have you tried a different browser? Have you tried incognito? This seems related to this issue? https://github.com/sct/overseerr/issues/539

**Comment by Zazou89** [comment]
Hey,
Thank you, I deleted cookies and it's ok now !
