### ISSUE TITLE
Overseerr crashing repeatedly due to unsuccessful plex auth

### ISSUE THREAD

**Issue by aptalca** [sct/overseerr#2253]
### Description

I had Overseerr down for a couple of months due to a move. After setting up the server again, I updated the docker image (linuxserver) and recreated the container. Once started, it gets into a crash loop with the below error.

### Version

1.27.0

### Steps to Reproduce

1. Start the container with existing data from 2 months ago.
2. Check the logs

### Screenshots

N/A

### Logs

```shell
[services.d] starting services
[services.d] done.
yarn run v1.22.10
$ NODE_ENV=production node dist/index.js
2021-11-01T19:50:23.681Z [[32minfo[39m]: Commit Tag: v1.27.0
2021-11-01T19:50:23.700Z [[32minfo[39m]: Starting Overseerr version 1.27.0

2021-11-01T19:50:25.150Z [[31merror[39m]: Error: Permission denied even after attempted authentication :( Wrong username and/or password maybe?

at /app/overseerr/node_modules/plex-api/lib/api.js:235:17
at new Promise (<anonymous>)
at PlexAPI._authenticate (/app/overseerr/node_modules/plex-api/lib/api.js:232:12)
at Request.onResponse [as _callback] (/app/overseerr/node_modules/plex-api/lib/api.js:208:26)
at Request.self.callback (/app/overseerr/node_modules/request/request.js:185:22)
at Request.emit (events.js:400:28)
at Request.<anonymous> (/app/overseerr/node_modules/request/request.js:1154:10)
at Request.emit (events.js:400:28)
at Gunzip.<anonymous> (/app/overseerr/node_modules/request/request.js:1076:12)
at Object.onceWrapper (events.js:519:28)
at Gunzip.emit (events.js:400:28)
at endReadableNT (internal/streams/readable.js:1334:12)
at processTicksAndRejections (internal/process/task_queues.js:82:21)
error Command failed with exit code 1.

info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

### Platform

desktop

### Device

N/A

### Operating System

Unraid (for server)

### Browser

N/A

### Additional Context

I may have changed the plex password since the last time I used Overseerr. If that's the case, how can I update that in Overseer without being able to bring up the gui?

Thanks

### Code of Conduct

- [X] I agree to follow Overseerr's Code of Conduct

**Comment by TheCatLady** [comment]
The minor libraries migration introduced in `1.27.0` fails if the Plex server is unreachable.

You can edit the `settings.json` file with valid Plex connection settings as a workaround.
