### ISSUE TITLE
Library Scan stalls on duplicate imdbId

### ISSUE THREAD

**Issue by garrettdowd** [sct/overseerr#244]
**Describe the bug**
Initial library scan stalled.

yarn run v1.22.4,
$ NODE_ENV=production node dist/index.js,
2020-12-14T05:29:02.604Z [info][Notifications]: Registered Notification Agents ,
2020-12-14T05:29:02.612Z [info][Jobs]: Scheduled jobs loaded ,
$ref: keywords ignored in schema at path "#/properties/requestedBy",
2020-12-14T05:29:02.879Z [info][SERVER]: Server ready on port 3000 ,
2020-12-14T05:30:00.039Z [info][Jobs]: Starting scheduled job: Plex Recently Added Sync ,
(node:29) UnhandledPromiseRejectionWarning: EntityNotFound: Could not find any entity of type "User" matching: {,
    "select": [,
        "id",,
        "plexToken",
    ],,
    "order": {,
        "id": "ASC",
    },
},
    at new EntityNotFoundError (/app/node_modules/typeorm/error/EntityNotFoundError.js:11:28),
    at /app/node_modules/typeorm/entity-manager/EntityManager.js:555:51,
    at async JobPlexSync.run (/app/dist/job/plexsync/index.js:220:27),
(node:29) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 2),
(node:29) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.,
2020-12-14T05:30:15.795Z [error]: Error checking user access: Plex is not configured! ,
2020-12-14T05:31:34.309Z [info][Plex Sync]: Beginning to process library: Movies ,
.
.
.
.
.
(node:29) UnhandledPromiseRejectionWarning: QueryFailedError: SQLITE_CONSTRAINT: UNIQUE constraint failed: media.imdbId,
    at new QueryFailedError (/app/node_modules/typeorm/error/QueryFailedError.js:11:28),
    at Statement.handler (/app/node_modules/typeorm/driver/sqlite/SqliteQueryRunner.js:76:38),
(node:29) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 3),
.
.
.

```

**Comment by sct** [comment]
This should be resolved on the latest `develop` tag. If you are still running into an issue, please re-open the ticket and let us know!
