### ISSUE TITLE
PGP keys are not validated on save and PGP errors are not properly logged

### ISSUE THREAD

**Issue by zekesonxx** [sct/overseerr#2510]
### Description

OpenPGP keys are not parsed when configured, only parsed when actually used. This means if some issue with a key is present, everything looks normal, but emails are not actually sent, and nothing PGP related shows up in the logs viewable on the webpage; just an eventual generic email issue when the SMTP connection times out

### Version

1.28.0

### Steps to Reproduce

1. Go to Settings->Notifications->Email, and configure a working email setup
2. Either in the PGP private key for sending, or PGP public key on an individual user, paste in a malformed PGP key.
3. Watch it be saved successfully with no errors
4. Perform an action that would trigger an email notification
5. Watch no errors appear in the Settings->Logs, until the SMTP connection eventually times out.
6. Watch errors like those below appear in stdout

### Logs

```shell
2022-02-06T22:40:10.887Z [info][Notifications]: Sending notification(s) for MEDIA_PENDING {"subject":"Those Magnificent Men in Their Flying Machines or How I Flew from London to Paris in 25 hours 11 minutes (1965)"}
(node:29) UnhandledPromiseRejectionWarning: Error: Misformed armored text
    at /app/node_modules/openpgp/dist/node/openpgp.min.js:2:25519
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
(Use `node --trace-warnings ...` to show where the warning was created)
(node:29) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 2706)
(node:29) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
2022-02-06T22:47:51.118Z [info][Notifications]: Sending notification(s) for MEDIA_PENDING {"subject":"Through My Window (2022)"}
(node:29) UnhandledPromiseRejectionWarning: Error: Unknown ASCII armor type
    at ge (/app/node_modules/openpgp/dist/node/openpgp.min.js:2:23439)
    at /app/node_modules/openpgp/dist/node/openpgp.min.js:2:25911
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
(node:29) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 2708)
2022-02-06T22:49:31.918Z [error][Notifications]: Error sending email notification {"recipient":"[...]","type":"MEDIA_PENDING","subject":"Through My Window (2022)","errorMessage":"Can't send mail - all recipients were rejected: 451 4.3.0 Error: queue file write error"}
```

### Platform

desktop

### Device

Laptop

### Operating System

Linux

### Browser

Firefox

### Code of Conduct

- [X] I agree to follow Overseerr's Code of Conduct

**Comment by TheCatLady** [comment]
It's not really possible to validate all inputs for the notification agents at the time of settings save (that's what the test functionality is for), but we definitely need to handle this error and log it.
