### ISSUE TITLE
Sonarr and Radarr Requests Failing

### ISSUE THREAD

**Issue by donMarine** [sct/overseerr#3128]
### Description

Requests to Radarr and Sonarr will periodically fail. I haven't noticed a reason or a pattern to the failures.

### Version

1.30.1

### Steps to Reproduce

Request a TV Show/Movie
Wait a few minutes

### Screenshots

![Screen Shot 2022-11-22 at 5 49 49 PM](https://user-images.githubusercontent.com/7416378/203437670-189a7fdb-c37a-40d3-8a85-1dff6c690a13.png)

### Logs

```shell
2022-11-22T22:47:49.097Z [error][Sonarr API]: Something went wrong while adding a series to Sonarr.{"errorMessage":"Series not found","options":{"languageProfileId":1,"monitored":true,"profileId":3,"rootFolderPath":"/tv","searchNow":true,"seasonFolder":true,"seasons":[1,2],"seriesType":"standard","tags":[],"title":"The Lord of the Rings: The Rings of Power","tvdbid":367506}}

2022-11-22T22:47:49.099Z [warn][Media Request]: Something went wrong sending series request to Sonarr, marking status as FAILED{"mediaId":1630,"requestId":165,"sonarrSeriesOptions":{"languageProfileId":1,"monitored":true,"profileId":3,"rootFolderPath":"/tv","searchNow":true,"seasonFolder":true,"seasons":[1,2],"seriesType":"standard","tags":[],"title":"The Lord of the Rings: The Rings of Power","tvdbid":367506}}
```

### Platform

desktop

### Device

MacBook Air

### Operating System

MacOS 12.6.2

### Browser

Safari

### Code of Conduct

- [X] I agree to follow Overseerr's Code of Conduct

**Comment by ceminess** [comment]
I receive this same issue.  I am able to add these movies in Radarr with no issue.  I receive the same error messages @donMarine mentions above.  

I am running on a Synology NAS docker container.  version 1.30.1

I also receive these below messages from the Radarr side:

> [POST /api/v3/movie]: constraint failed
> UNIQUE constraint failed: MovieMetadata.TmdbId
> 

> code = Constraint (19), message = System.Data.SQLite.SQLiteException (0x800027AF): constraint failed
> UNIQUE constraint failed: MovieMetadata.TmdbId
>    at System.Data.SQLite.SQLite3.Reset(SQLiteStatement stmt)
>    at System.Data.SQLite.SQLite3.Step(SQLiteStatement stmt)
>    at System.Data.SQLite.SQLiteDataReader.NextResult()
>    at System.Data.SQLite.SQLiteDataReader..ctor(SQLiteCommand cmd, CommandBehavior behave)
>    at System.Data.SQLite.SQLiteCommand.ExecuteReader(CommandBehavior behavior)
>    at Dapper.SqlMapper.ExecuteReaderWithFlagsFallback(IDbCommand cmd, Boolean wasClosed, CommandBehavior behavior) in /_/Dapper/SqlMapper.cs:line 1075
>    at Dapper.SqlMapper.QueryMultipleImpl(IDbConnection cnn, CommandDefinition& command) in /_/Dapper/SqlMapper.cs:line 1058
>    at NzbDrone.Core.Datastore.BasicRepository`1.Insert(IDbConnection connection, IDbTransaction transaction, TModel model) in D:\a\1\s\src\NzbDrone.Core\Datastore\BasicRepository.cs:line 188
>    at NzbDrone.Core.Datastore.BasicRepository`1.InsertMany(IList`1 models) in D:\a\1\s\src\NzbDrone.Core\Datastore\BasicRepository.cs:line 210
>    at NzbDrone.Core.Movies.MovieMetadataRepository.UpsertMany(List`1 data) in D:\a\1\s\src\NzbDrone.Core\Movies\MovieMetadataRepository.cs:line 117
>    at NzbDrone.Core.Movies.AddMovieService.AddMovie(Movie newMovie) in D:\a\1\s\src\NzbDrone.Core\Movies\AddMovieService.cs:line 57
>    at Radarr.Api.V3.Movies.MovieController.AddMovie(MovieResource moviesResource) in D:\a\1\s\src\Radarr.Api.V3\Movies\MovieController.cs:line 209
>    at lambda_method460(Closure , Object , Object[] )
>    at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.SyncObjectResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
>    at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeActionMethodAsync()
>    at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
>    at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeNextActionFilterAsync()
> --- End of stack trace from previous location ---
>    at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
>    at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
>    at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeInnerFilterAsync()
> --- End of stack trace from previous location ---
>    at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeFilterPipelineAsync>g__Awaited|20_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
>    at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
>    at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
>    at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
>    at Radarr.Http.Middleware.BufferingMiddleware.InvokeAsync(HttpContext context) in D:\a\1\s\src\Radarr.Http\Middleware\BufferingMiddleware.cs:line 28
>    at Radarr.Http.Middleware.IfModifiedMiddleware.InvokeAsync(HttpContext context) in D:\a\1\s\src\Radarr.Http\Middleware\IfModifiedMiddleware.cs:line 41
>    at Radarr.Http.Middleware.CacheHeaderMiddleware.InvokeAsync(HttpContext context) in D:\a\1\s\src\Radarr.Http\Middleware\CacheHeaderMiddleware.cs:line 33
>    at Radarr.Http.Middleware.UrlBaseMiddleware.InvokeAsync(HttpContext context) in D:\a\1\s\src\Radarr.Http\Middleware\UrlBaseMiddleware.cs:line 27
>    at Radarr.Http.Middleware.VersionMiddleware.InvokeAsync(HttpContext context) in D:\a\1\s\src\Radarr.Http\Middleware\VersionMiddleware.cs:line 28
>    at Microsoft.AspNetCore.Authorization.Policy.AuthorizationMiddlewareResultHandler.HandleAsync(RequestDelegate next, HttpContext context, AuthorizationPolicy policy, PolicyAuthorizationResult authorizeResult)
>    at Microsoft.AspNetCore.Authorization.AuthorizationMiddleware.Invoke(HttpContext context)
>    at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
>    at Microsoft.AspNetCore.Diagnostics.ExceptionHandlerMiddleware.<Invoke>g__Awaited|6_0(ExceptionHandlerMiddleware middleware, HttpContext context, Task task)

**Comment by OwsleyJr** [comment]
What version of Sonarr and Radarr are you guys running?

**Comment by maraouf** [comment]
Facing the same issue
Using Overseerr 1.30.1 over snap

Sample error

2022-12-01T08:30:00.965Z [info][Watchlist Sync]: Creating media request from user's Plex Watchlist {"userId":1,"mediaTitle":"The Sum of All Fears"}
2022-12-01T08:30:01.774Z [info][Notifications]: Sending notification(s) for MEDIA_AUTO_APPROVED {"subject":"The Sum of All Fears (2002)"}
2022-12-01T08:30:01.775Z [debug][Notifications]: Sending LunaSea notification {"type":"MEDIA_AUTO_APPROVED","subject":"The Sum of All Fears (2002)"}
2022-12-01T08:30:01.780Z [info][Notifications]: Sending notification(s) for MEDIA_AUTO_REQUESTED {"subject":"The Sum of All Fears (2002)"}
2022-12-01T08:30:01.780Z [debug][Notifications]: Sending email notification {"recipient":"m.a.raouf","type":"MEDIA_AUTO_REQUESTED","subject":"The Sum of All Fears (2002)"}
2022-12-01T08:31:42.853Z [error][Radarr]: Failed to add movie to Radarr. This might happen if the movie already exists, in which case you can safely ignore this error. {"errorMessage":"Movie not found","options":{"profileId":1,"qualityProfileId":1,"rootFolderPath":"/mnt/wdmycloud/Movies","minimumAvailability":"released","title":"The Sum of All Fears","tmdbId":4614,"year":2002,"monitored":true,"tags":[],"searchNow":true}}
2022-12-01T08:31:42.854Z [warn][Media Request]: Something went wrong sending movie request to Radarr, marking status as FAILED {"requestId":561,"mediaId":3012,"radarrMovieOptions":{"profileId":1,"qualityProfileId":1,"rootFolderPath":"/mnt/wdmycloud/Movies","minimumAvailability":"released","title":"The Sum of All Fears","tmdbId":4614,"year":2002,"monitored":true,"tags":[],"searchNow":true}}
2022-12-01T08:31:42.864Z [info][Notifications]: Sending notification(s) for MEDIA_FAILED {"subject":"The Sum of All Fears (2002)"}
2022-12-01T08:31:42.866Z [debug][Notifications]: Sending LunaSea notification {"type":"MEDIA_FAILED","subject":"The Sum of All Fears (2002)"}
2022-12-01T08:31:43.033Z [debug][Notifications]: Sending email notification {"recipient":"m.a.raouf","type":"MEDIA_FAILED","subject":"The Sum of All Fears (2002)"}
2022-12-01T11:10:01.859Z [info][Watchlist Sync]: Creating media request from user's Plex Watchlist {"userId":1,"mediaTitle":"The Sum of All Fears"}
2022-12-01T11:10:02.172Z [info][Notifications]: Sending notification(s) for MEDIA_AUTO_APPROVED {"subject":"The Sum of All Fears (2002)"}
2022-12-01T11:10:02.172Z [debug][Notifications]: Sending LunaSea notification {"type":"MEDIA_AUTO_APPROVED","subject":"The Sum of All Fears (2002)"}
2022-12-01T11:10:02.175Z [info][Notifications]: Sending notification(s) for MEDIA_AUTO_REQUESTED {"subject":"The Sum of All Fears (2002)"}
2022-12-01T11:10:02.176Z [debug][Notifications]: Sending email notification {"recipient":"m.a.raouf","type":"MEDIA_AUTO_REQUESTED","subject":"The Sum of All Fears (2002)"}
2022-12-01T11:12:12.244Z [error][Radarr]: Failed to add movie to Radarr. This might happen if the movie already exists, in which case you can safely ignore this error. {"errorMessage":"Movie not found","options":{"profileId":1,"qualityProfileId":1,"rootFolderPath":"/mnt/wdmycloud/Movies","minimumAvailability":"released","title":"The Sum of All Fears","tmdbId":4614,"year":2002,"monitored":true,"tags":[],"searchNow":true}}
2022-12-01T11:12:12.245Z [warn][Media Request]: Something went wrong sending movie request to Radarr, marking status as FAILED {"requestId":566,"mediaId":3012,"radarrMovieOptions":{"profileId":1,"qualityProfileId":1,"rootFolderPath":"/mnt/wdmycloud/Movies","minimumAvailability":"released","title":"The Sum of All Fears","tmdbId":4614,"year":2002,"monitored":true,"tags":[],"searchNow":true}}
2022-12-01T11:12:12.251Z [info][Notifications]: Sending notification(s) for MEDIA_FAILED {"subject":"The Sum of All Fears (2002)"}

Movie doesnt exist on Radarr

**Comment by OwsleyJr** [comment]
Duplicate of #3090

**Comment by johnistheman** [comment]
This is not a duplicate of #3090. That issue is able the "Retry" button not working. This issue is about the requests failing in the first place.
