### ISSUE TITLE
Cant add TV Shows

### ISSUE THREAD

**Issue by henrikrox** [sct/overseerr#323]
Movies will request fine, i can add sonar no problem, says its connected, when i add tv shows i get

```
2020-12-15T22:02:45.129Z [info][Media Request]: Sent request to Sonarr | stdout
-- | --
2020-12-15T22:02:45.261Z [error][Sonarr API]: Request failed with status code 400 {"error":{"message":"Request failed with status code 400","name":"Error","stack":"Error: Request failed with status code 400\n    at createError (/app/node_modules/axios/lib/core/createError.js:16:15)\n    at settle (/app/node_modules/axios/lib/core/settle.js:17:12)\n    at IncomingMessage.handleStreamEnd (/app/node_modules/axios/lib/adapters/http.js:244:11)\n    at IncomingMessage.emit (events.js:327:22)\n    at endReadableNT (_stream_readable.js:1220:12)\n    at processTicksAndRejections (internal/process/task_queues.js:84:21)","config":{"url":"/series","method":"post","data":"{\"tvdbId\":361753,\"title\":\"The Mandalorian\",\"profileId\":1,\"seasons\":[{\"seasonNumber\":1,\"monitored\":false},{\"seasonNumber\":2,\"monitored\":true}],\"monitored\":true,\"rootFolderPath\":\"/data/TV Shows/\",\"addOptions\":{\"ignoreEpisodesWithFiles\":true,\"searchForMissingEpisodes\":true}}","headers":{"Accept":"application/json, text/plain, */*","Content-Type":"application/json;charset=utf-8","User-Agent":"axios/0.21.0","Content-Length":272},"params":{"apikey":"3661ae2a99084b829bbd4eaf8143258e"},"baseURL":"http://10.0.0.10:32786/api","transformRequest":[null],"transformResponse":[null],"timeout":0,"xsrfCookieName":"XSRF-TOKEN","xsrfHeaderName":"X-XSRF-TOKEN","maxContentLength":-1,"maxBodyLength":-1}}} | stdout
-- | --
(node:28) UnhandledPromiseRejectionWarning: Error: Failed to add series | stdout
-- | --
at SonarrAPI.addSeries (/app/dist/api/sonarr.js:74:19) | stdout
-- | --
at runMicrotasks (<anonymous>) | stdout
-- | --
at processTicksAndRejections (internal/process/task_queues.js:97:5) | stdout
-- | --
(node:28) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 4)





```

**Comment by samwiseg0** [comment]
Please fill out the issues template that is provided. Secondly, What version of sonarr are you running?

**Comment by samwiseg0** [comment]
Closing as https://github.com/sct/overseerr/issues/373 provides more details
